// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wwhomnnlzhyikezpulyc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind3aG9tbm5semh5aWtlenB1bHljIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzNTM1NDcsImV4cCI6MjA2MzkyOTU0N30.cM_SYYUDRhGX-5KWouXtcTSmbOzs8KWFUOOVHUzSeFI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);